name: Matrix Sandbox

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  set-matrix:
    name: Setup Matrix
    runs-on: ubuntu-latest
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2

      - name: Parse and set trader usernames
        id: set-usernames
        run: echo "::set-output name=matrix::$(cat ./usernames.json)"
    outputs:
      matrix: ${{ steps.set-usernames.outputs.matrix }}

  test-env-matrix:
    name: Hello World
    needs: set-matrix
    strategy:
      matrix:
        username: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo ${{ matrix.username }}
