name: Matrix Sandbox

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-usernames
        run: echo "::set-output name=matrix::${{ secrets.usernames }}"
    outputs:
      matrix: ${{ steps.set-usernames.outputs.matrix }}

  test-env-matrix:
    needs: set-matrix
    strategy:
      matrix:
        username: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo ${{ matrix.username }}
